### ISSUE TITLE
Update to latest prometheus.erl

### ISSUE THREAD

**Issue by yurrriq** [elli-lib/elli_prometheus#10]
Might need your help on this, @deadtrickster.

**Comment by deadtrickster** [comment]
Sure, can this wait for a couple of days?

**Comment by yurrriq** [comment]
Definitely :smile:

**Comment by deadtrickster** [comment]
Once https://github.com/elli-lib/elli/issues/7 resolved I'll update this.

Questions:
https://github.com/elli-lib/elli_prometheus/blob/master/src/elli_prometheus.erl#L61 {0,0,0} defaults here. I don't like them, why are they needed? I glanced through elli code, can it really happen that those times wouldn't be set? 
Why user_ times and not request_ times? maybe we want both?

**Comment by deadtrickster** [comment]
Also time units, we can stay with microseconds but now when the is new timing system, we can use seconds to follow Prometheus best practices guide. What you think? You said you have grafana dashboard setup already.

**Comment by yurrriq** [comment]
The dashboard is very basic and I'd rather follow the Prometheus best practices guide than avoid tweaking the dashboard.

**Comment by yurrriq** [comment]
This is resolved, right? Feel free to close, @deadtrickster.
