### ISSUE TITLE
Fix dialyzer issue

### ISSUE THREAD

**Issue by yurrriq** [elli-lib/elli_prometheus#19]
See https://travis-ci.org/elli-lib/elli_prometheus/jobs/185942752#L264

**Comment by deadtrickster** [comment]
I have no idea what it wants :-) Maybe it's my morning

**Comment by yurrriq** [comment]
I'll take a look in my morning :wink:

**Comment by yurrriq** [comment]
https://travis-ci.org/elli-lib/elli_prometheus/builds/640020870
