### ISSUE TITLE
Publish Hex package

### ISSUE THREAD

**Issue by yurrriq** [elli-lib/elli_prometheus#8]
Once we get to a stable-feeling release (see #4, for example) and have good tests (#6).

**Comment by tsloughter** [comment]
@yurrriq can we publish this now? I'm switching to prometheus at work and prefer to use hex packages :)

**Comment by yurrriq** [comment]
Yeah, I think we can publish. Fixes for #15 and #17 can wait till the next release. Anything else you wanna sneak in first, @deadtrickster?

**Comment by deadtrickster** [comment]
Compression is working, @tsloughter let me know if you need basic auth. Otherwise I think we are ready.

**Comment by tsloughter** [comment]
Nope, no auth needed for me :)

**Comment by yurrriq** [comment]
Published [0.1.0](https://github.com/elli-lib/elli_prometheus/releases/tag/0.1.0) to [Hex](https://hex.pm/packages/elli_prometheus/0.1.0).
